from fastapi import FastAPI, HTTPException
from loguru import logger

from src.model.load_model import DoubleItModel
from src.model.schema import InputData

# Inicializaci√≥n de la aplicaci√≥n FastAPI
app = FastAPI(title="Servicio de Inferencia - DoubleIt")
logger.info("üöÄ Aplicaci√≥n FastAPI iniciada.")

# Cargar el modelo al iniciar la aplicaci√≥n
try:
    model: DoubleItModel = DoubleItModel()
    logger.info("‚úÖ Modelo cargado exitosamente.")
except Exception as err:
    logger.exception("‚ùå Error al cargar el modelo.")
    raise RuntimeError("Error.") from err


@app.post("/predict", response_model=dict[str, list])
def predict(data: InputData) -> dict[str, list]:
    """
    Endpoint que recibe una lista de n√∫meros enteros y devuelve la predicci√≥n generada por el modelo.

    Par√°metros:
    ----------
    data : InputData
        Objeto con la lista de enteros a procesar.

    Retorna:
    -------
    dict[str, list]
        Diccionario con la entrada original y el resultado de la predicci√≥n.
    """
    logger.info("üì• Solicitud de predicci√≥n recibida.")
    try:
        resultado = model.predict(data.values)
        logger.info(f"‚úÖ Predicci√≥n generada correctamente: {resultado}")
    except ValueError as err:
        logger.exception("‚ùå Error de validaci√≥n en los datos de entrada.")
        raise HTTPException(status_code=400, detail="Entrada inv√°lida") from err
    else:
        return {"input": data.values, "output": resultado}
